CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Foods" (
    "Id" INTEGER NOT NULL,
    "UserId" INTEGER NOT NULL,
    "Title" TEXT NOT NULL,
    "Quantity" REAL NOT NULL,
    "Unit" TEXT NOT NULL,
    "Calories" INTEGER NOT NULL,
    "Fats" INTEGER NOT NULL,
    "Carbs" INTEGER NOT NULL,
    "Proteins" INTEGER NOT NULL,
    CONSTRAINT "PK_Foods" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230503153053_InitialMigration', '7.0.5');

COMMIT;

START TRANSACTION;

CREATE TABLE "Meals" (
    "Id" INTEGER NOT NULL,
    "UserId" INTEGER NOT NULL,
    "Title" TEXT NOT NULL,
    CONSTRAINT "PK_Meals" PRIMARY KEY ("Id")
);

CREATE TABLE "MealFoods" (
    "Id" INTEGER NOT NULL,
    "UserId" INTEGER NOT NULL,
    "MealId" INTEGER NOT NULL,
    "FoodId" INTEGER NOT NULL,
    "DesiredQuantity" REAL NOT NULL,
    CONSTRAINT "PK_MealFoods" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MealFoods_Foods_FoodId" FOREIGN KEY ("FoodId") REFERENCES "Foods" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MealFoods_Meals_MealId" FOREIGN KEY ("MealId") REFERENCES "Meals" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_MealFoods_FoodId" ON "MealFoods" ("FoodId");

CREATE INDEX "IX_MealFoods_MealId" ON "MealFoods" ("MealId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230505214850_AddMealAndMealFood', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "MealFoods" DROP CONSTRAINT "PK_MealFoods";

DROP INDEX "IX_MealFoods_MealId";

ALTER TABLE "MealFoods" DROP COLUMN "UserId";

ALTER TABLE "MealFoods" ADD CONSTRAINT "PK_MealFoods" PRIMARY KEY ("MealId", "FoodId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230506115359_RemoveUserIdFromMealFood', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "MealFoods" DROP COLUMN "Id";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230506120226_RemoveIdFromMealFood', '7.0.5');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230506121812_RenameFoodToBaseFoodOnMealFood', '7.0.5');

COMMIT;

START TRANSACTION;

CREATE TABLE "MealPlans" (
    "Id" INTEGER NOT NULL,
    "UserId" INTEGER NOT NULL,
    "Title" TEXT NOT NULL,
    "RequiredCalories" INTEGER NOT NULL,
    "RequiredFats" INTEGER NOT NULL,
    "RequiredCarbs" INTEGER NOT NULL,
    "RequiredProteins" INTEGER NOT NULL,
    CONSTRAINT "PK_MealPlans" PRIMARY KEY ("Id")
);

CREATE TABLE "MealPlanMeals" (
    "MealPlanId" INTEGER NOT NULL,
    "MealId" INTEGER NOT NULL,
    CONSTRAINT "PK_MealPlanMeals" PRIMARY KEY ("MealId", "MealPlanId"),
    CONSTRAINT "FK_MealPlanMeals_MealPlans_MealPlanId" FOREIGN KEY ("MealPlanId") REFERENCES "MealPlans" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MealPlanMeals_Meals_MealId" FOREIGN KEY ("MealId") REFERENCES "Meals" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_MealPlanMeals_MealPlanId" ON "MealPlanMeals" ("MealPlanId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230506183425_AddMealPlanMealsAndMealPlans', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "Meals" ALTER COLUMN "UserId" TYPE bigint;

ALTER TABLE "Meals" ALTER COLUMN "Title" TYPE text;

ALTER TABLE "Meals" ALTER COLUMN "Id" TYPE bigint;
ALTER TABLE "Meals" ALTER COLUMN "Id" DROP DEFAULT;
ALTER TABLE "Meals" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "MealPlans" ALTER COLUMN "UserId" TYPE bigint;

ALTER TABLE "MealPlans" ALTER COLUMN "Title" TYPE text;

ALTER TABLE "MealPlans" ALTER COLUMN "RequiredProteins" TYPE integer;

ALTER TABLE "MealPlans" ALTER COLUMN "RequiredFats" TYPE integer;

ALTER TABLE "MealPlans" ALTER COLUMN "RequiredCarbs" TYPE integer;

ALTER TABLE "MealPlans" ALTER COLUMN "RequiredCalories" TYPE integer;

ALTER TABLE "MealPlans" ALTER COLUMN "Id" TYPE bigint;
ALTER TABLE "MealPlans" ALTER COLUMN "Id" DROP DEFAULT;
ALTER TABLE "MealPlans" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "MealPlanMeals" ALTER COLUMN "MealPlanId" TYPE bigint;

ALTER TABLE "MealPlanMeals" ALTER COLUMN "MealId" TYPE bigint;

ALTER TABLE "MealFoods" ALTER COLUMN "DesiredQuantity" TYPE double precision;

ALTER TABLE "MealFoods" ALTER COLUMN "FoodId" TYPE bigint;

ALTER TABLE "MealFoods" ALTER COLUMN "MealId" TYPE bigint;

ALTER TABLE "Foods" ALTER COLUMN "UserId" TYPE bigint;

ALTER TABLE "Foods" ALTER COLUMN "Unit" TYPE text;

ALTER TABLE "Foods" ALTER COLUMN "Title" TYPE text;

ALTER TABLE "Foods" ALTER COLUMN "Quantity" TYPE double precision;

ALTER TABLE "Foods" ALTER COLUMN "Proteins" TYPE integer;

ALTER TABLE "Foods" ALTER COLUMN "Fats" TYPE integer;

ALTER TABLE "Foods" ALTER COLUMN "Carbs" TYPE integer;

ALTER TABLE "Foods" ALTER COLUMN "Calories" TYPE integer;

ALTER TABLE "Foods" ALTER COLUMN "Id" TYPE bigint;
ALTER TABLE "Foods" ALTER COLUMN "Id" DROP DEFAULT;
ALTER TABLE "Foods" ALTER COLUMN "Id" ADD GENERATED ALWAYS AS IDENTITY;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230507001738_ChangeFoodIdToBeIdentityType', '7.0.5');

COMMIT;

START TRANSACTION;

ALTER TABLE "Meals" ALTER COLUMN "Id" SET GENERATED ALWAYS;

ALTER TABLE "MealPlans" ALTER COLUMN "Id" SET GENERATED ALWAYS;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230507002329_ChangeMealIdAndMealPlanIdToBeIdentityType', '7.0.5');

COMMIT;


