application:
  audience: ${AUTH0_AUDIENCE}
  client-origin-url: ${CLIENT_ORIGIN_URL}

server:
  error:
    whitelabel:
      enabled: false
  port: ${PORT}
  contextPath: /

spring:
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  data:
    rest:
      base-path: /api
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${AUTH0_DOMAIN}/
  web:
    resources:
      add-mappings: false